version: '3'
services:
  web:
    build: .
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=development
      - INVENTREE_API_TOKEN=${INVENTREE_API_TOKEN}
      - INVENTREE_BASE_URL=${INVENTREE_BASE_URL}
      - PYTHONUNBUFFERED=1
    command: flask run --host=0.0.0.0 --port=5555